// === CHAR RENDERING ===
function dCh(ch,wx,wy,col,sz){X.fillStyle=col;setFont(fontPx(sz||18));X.textAlign='center';X.textBaseline='middle';X.fillText(ch,wx,wy);}
function dChG(ch,wx,wy,col,sz,gl){X.shadowColor=col;X.shadowBlur=gl||6;dCh(ch,wx,wy,col,sz);X.shadowBlur=0;}

// === UTILITIES ===
function totalSIG(){return(altarSeed?1:0)+seeds.length;}
function dist(a,b,c,d){return Math.sqrt((c-a)**2+(d-b)**2);}
function nearA(gx,gy,r){return dist(gx,gy,CX,CY)<r;}
function isOcc(gx,gy){if(gx<0||gx>=GW||gy<0||gy>=GH)return true;return grid[gy][gx]!=='empty';}
function isOccNR(gx,gy){if(gx<0||gx>=GW||gy<0||gy>=GH)return true;if(grid[gy][gx]!=='empty'&&grid[gy][gx]!=='flower')return true;if(river.has(`${gx},${gy}`))return true;if(fireTiles.has(`${gx},${gy}`))return true;if(burnedTiles[`${gx},${gy}`]!==undefined)return true;return false;}
function isFB(gx,gy){return fireTiles.has(`${gx},${gy}`)||burnedTiles[`${gx},${gy}`]!==undefined;}
function cntB(){let n=0;for(const b of bushes)if(b.st==='bush')n++;return n;}
function cntT(){let n=0;for(const t of trees)if(t.st==='tree')n++;return n;}
function cntDeer(){let n=0;for(const d of deers)if(d.joined)n++;return n;}
function isRA(gx,gy){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(dx===0&&dy===0)continue;if(river.has(`${gx+dx},${gy+dy}`))return true;}return false;}
function isRT(gx,gy){return river.has(`${gx},${gy}`);}
function disc_(k,m){if(disc[k])return;disc[k]=true;discQ.push(m);triggerBorderFlash();}
function updD(dt){const bn=EL['discovery-banner'];if(discT>0){discT-=dt;if(discT<=0){bn.classList.remove('show');setTimeout(()=>{if(discQ.length)showD();},500);}}else if(discQ.length)showD();}
function showD(){if(!discQ.length)return;const bn=EL['discovery-banner'];bn.textContent=discQ.shift();bn.classList.add('show');discT=3.5;}
function showTB(){taskBT=2.5;EL['task-bubble'].classList.add('show');triggerBorderFlash();playS('mission');}
function updTB(dt){if(taskBT>0){taskBT-=dt;if(taskBT<=0)EL['task-bubble'].classList.remove('show');}}
function triggerBorderFlash(){const el=EL['border-flash'];el.classList.remove('active');void el.offsetWidth;el.classList.add('active');setTimeout(()=>el.classList.remove('active'),800);}
// Early on the brackets come back sooner and also point at somewhere to plant,
// so a player who puts the seed in hand and then stalls still gets a nudge.
function ctaIdle(){return tasksDone.has(TASKS[1].id)?CTA_IDLE:3;}
function updateCTA(dt){lastPA+=dt;if(ctaTarget){ctaTimer-=dt;if(ctaTimer<=0)ctaTarget=null;return;}if(lastPA<ctaIdle())return;if(sel&&sel.type==='aS'){ctaTarget={type:'plantSpot'};ctaTimer=2.5;lastPA=0;return;}if(altarSeed&&totalSP<3){ctaTarget={type:'altarSeed'};ctaTimer=2;lastPA=0;return;}for(const t of trees){if(t.st==='tree'&&t.hasSeed){ctaTarget={type:'tST',ref:t};ctaTimer=2;lastPA=0;return;}}if(altarSeed){ctaTarget={type:'altarSeed'};ctaTimer=2;lastPA=0;return;}for(const b of beavers){if(b.state==='idle'&&!b.chop&&cntT()>0){ctaTarget={type:'beaver',ref:b};ctaTimer=2;lastPA=0;return;}}}
// Matches the spot updTut() points a first-time player at, so the two prompts
// never disagree about where to plant.
function ctaPlantSpot(){const a=2.5,d=AR+4;return{x:(CX+Math.cos(a)*d)*T+T/2,y:(CY+Math.sin(a)*d)*T+T/2};}
function drawCTA(){if(!ctaTarget)return;const alpha=0.5+Math.sin(tt*5)*0.35;const col=`rgba(255,255,255,${alpha})`;if(ctaTarget.type==='plantSpot'){const p=ctaPlantSpot();dCh('{',p.x-12,p.y,col,22);dCh('}',p.x+12,p.y,col,22);dCh('\u00B7',p.x,p.y,col,16);return;}if(ctaTarget.type==='altarSeed'){const mx=CX*T+T/2,my=CY*T+T/2;dCh('{',mx-12,my,col,22);dCh('}',mx+12,my,col,22);}else if(ctaTarget.type==='tST'&&ctaTarget.ref){const t=ctaTarget.ref;dCh('{',t.gx*T,t.gy*T+T/2,col,20);dCh('}',t.gx*T+T,t.gy*T+T/2,col,20);}else if(ctaTarget.type==='beaver'&&ctaTarget.ref){const b=ctaTarget.ref;dCh('{',b.x-14,b.y,col,20);dCh('}',b.x+14,b.y,col,20);}}

// === PARTICLES ===
function spawnP(wx,wy,c1,c2){for(let i=0;i<10;i++){const a=Math.random()*Math.PI*2,s=15+Math.random()*25;particles.push({x:wx,y:wy,vx:Math.cos(a)*s,vy:Math.sin(a)*s-12,life:0.4+Math.random()*0.5,mL:0.9,color:Math.random()>0.5?c1:c2,ch:['·','*','+','°'][Math.floor(Math.random()*4)]});}}
function updP(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=30*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1);}}
function drawP(){for(const p of particles){X.globalAlpha=Math.max(0,p.life/p.mL);dChG(p.ch,p.x,p.y,p.color,12,4);}X.globalAlpha=1;}

function updAltar(dt){if(altarSeed)return;if(totalSIG()>=MAX_SEEDS)return;aCD-=dt*1000;if(aCD<=0){altarSeed=true;aCD=SCD;}}
function mkA(type,x,y){return{type,x:x*T+T/2,y:y*T+T/2,tX:null,tY:null,state:'idle',stT:1+Math.random()*3,carry:null,speed:type==='beaver'?25:type==='frog'?20:type==='bee'?55:45,idleT:1+Math.random()*4,mv:false,fR:true,chop:null,tSeed:null,pSpot:null,isFirst:false,hPF:false};}
function wT(a,r){for(let attempt=0;attempt<20;attempt++){const ang=Math.random()*Math.PI*2,d=40+Math.random()*r;const tx=Math.max(T,Math.min(MW-T,a.x+Math.cos(ang)*d)),ty=Math.max(T,Math.min(MH-T,a.y+Math.sin(ang)*d));const gx=Math.floor(tx/T),gy=Math.floor(ty/T);if(!isFB(gx,gy))return{x:tx,y:ty};}return{x:a.x,y:a.y};}function mvTo(a,tx,ty,dt){const dx=tx-a.x,dy=ty-a.y,d=Math.sqrt(dx*dx+dy*dy);if(d<4){a.mv=false;return true;}const s=a.speed*dt;let nx=a.x+(dx/d)*Math.min(s,d),ny=a.y+(dy/d)*Math.min(s,d);const ngx=Math.floor(nx/T),ngy=Math.floor(ny/T);if(isFB(ngx,ngy)){const pX=-dy/d,pY=dx/d;nx=a.x+pX*s*(Math.random()>0.5?2:-2);ny=a.y+pY*s*(Math.random()>0.5?2:-2);const g2=Math.floor(nx/T),g3=Math.floor(ny/T);if(isFB(g2,g3)){a.state='idle';a.idleT=0.5;a.mv=false;return false;}}a.x=Math.max(T,Math.min(MW-T,nx));a.y=Math.max(T,Math.min(MH-T,ny));a.mv=true;if(dx>0)a.fR=true;else if(dx<0)a.fR=false;return false;}
function mvAv(a,tx,ty,dt){const dx=tx-a.x,dy=ty-a.y,d=Math.sqrt(dx*dx+dy*dy);if(d<6){a.mv=false;return true;}const s=a.speed*dt;let nx=a.x+(dx/d)*Math.min(s,d),ny=a.y+(dy/d)*Math.min(s,d);const gx=Math.floor(nx/T),gy=Math.floor(ny/T);if(gx>=0&&gx<GW&&gy>=0&&gy<GH){const c=grid[gy][gx];if(a.type==='beaver'&&(c==='tree'||c==='bush'||c==='treeSprout'||c==='bushSprout')){if(!(a.chop&&a.chop.gx===gx&&a.chop.gy===gy)){const pX=-dy/d,pY=dx/d;nx=a.x+pX*s*(Math.random()>0.5?2:-2);ny=a.y+pY*s*(Math.random()>0.5?2:-2);}}}a.x=Math.max(T,Math.min(MW-T,nx));a.y=Math.max(T,Math.min(MH-T,ny));a.mv=true;if(dx>0)a.fR=true;else if(dx<0)a.fR=false;return false;}
function fSpot(){for(let i=0;i<30;i++){const a=Math.random()*Math.PI*2,d=AR+2+Math.random()*15;const gx=Math.floor(CX+Math.cos(a)*d),gy=Math.floor(CY+Math.sin(a)*d);if(gx>=1&&gx<GW-1&&gy>=1&&gy<GH-1&&!isOccNR(gx,gy)&&!nearA(gx,gy,AR))return{x:gx,y:gy};}return null;}
function fTSpot(){for(let i=0;i<40;i++){const a=Math.random()*Math.PI*2,d=AR+4+Math.random()*20;const gx=Math.floor(CX+Math.cos(a)*d),gy=Math.floor(CY+Math.sin(a)*d);if(gx>=1&&gx<GW-1&&gy>=1&&gy<GH-1&&!isOccNR(gx,gy)&&!nearA(gx,gy,AR)){let tc=false;for(const t of trees)if(dist(gx,gy,t.gx,t.gy)<2){tc=true;break;}if(!tc)return{x:gx,y:gy};}}return null;}

// === AI ===
function updRBi(b,dt){b.stT-=dt;if(b.state==='idle'){b.mv=false;b.idleT-=dt;if(b.idleT<=0){if(!b.carry&&seeds.length>0&&Math.random()<0.4){const s=seeds[Math.floor(Math.random()*seeds.length)];b.tX=s.gx*T+T/2;b.tY=s.gy*T+T/2;b.tSeed=s;b.state='gSeed';}else{const t=wT(b,120);b.tX=t.x;b.tY=t.y;b.state='wander';b.stT=3+Math.random()*4;}b.idleT=2+Math.random()*5;}}else if(b.state==='wander'){if(mvTo(b,b.tX,b.tY,dt)||b.stT<=0){b.state='idle';b.idleT=1+Math.random()*3;}}else if(b.state==='gSeed'){if(!b.tSeed||!seeds.includes(b.tSeed)){b.state='idle';return;}if(mvTo(b,b.tX,b.tY,dt)){const i=seeds.indexOf(b.tSeed);if(i!==-1){seeds.splice(i,1);grid[b.tSeed.gy][b.tSeed.gx]='empty';b.carry='seed';const sp=fSpot();if(sp){b.tX=sp.x*T+T/2;b.tY=sp.y*T+T/2;b.pSpot=sp;b.state='gPlant';}else{b.carry=null;b.state='idle';}}else b.state='idle';}}else if(b.state==='gPlant'){if(mvTo(b,b.tX,b.tY,dt)){const s=b.pSpot;if(s&&!isOccNR(s.x,s.y)){grid[s.y][s.x]='bushSprout';bushes.push({gx:s.x,gy:s.y,st:'sprout',timer:3+Math.random()*6});disc_('bushSprout','Sprouts detected');}b.carry=null;b.state='idle';b.idleT=2+Math.random()*3;}}}
function updBBi(b,dt){b.stT-=dt;if(b.state==='idle'){b.mv=false;b.idleT-=dt;if(b.idleT<=0){if(b.isFirst&&!b.hPF&&trees.length===0){const sp=fTSpot();if(sp){b.tX=sp.x*T+T/2;b.tY=sp.y*T+T/2;b.pSpot=sp;b.carry='treeSeed';b.state='gPlant';b.hPF=true;return;}}if(!b.carry&&tSP.length>0&&trees.length<MT&&Math.random()<0.5){const s=tSP[Math.floor(Math.random()*tSP.length)];b.tX=s.gx*T+T/2;b.tY=s.gy*T+T/2;b.tSeed=s;b.state='gSeed';}else{const t=wT(b,150);b.tX=t.x;b.tY=t.y;b.state='wander';b.stT=3+Math.random()*5;}b.idleT=2+Math.random()*5;}}else if(b.state==='wander'){if(mvTo(b,b.tX,b.tY,dt)||b.stT<=0){b.state='idle';b.idleT=1+Math.random()*3;}}else if(b.state==='gSeed'){if(!b.tSeed||!tSP.includes(b.tSeed)){b.state='idle';return;}if(mvTo(b,b.tX,b.tY,dt)){const i=tSP.indexOf(b.tSeed);if(i!==-1){tSP.splice(i,1);grid[b.tSeed.gy][b.tSeed.gx]='empty';b.carry='treeSeed';const sp=fTSpot();if(sp){b.tX=sp.x*T+T/2;b.tY=sp.y*T+T/2;b.pSpot=sp;b.state='gPlant';}else{b.carry=null;b.state='idle';}}else b.state='idle';}}else if(b.state==='gPlant'){if(mvTo(b,b.tX,b.tY,dt)){const s=b.pSpot;if(s&&!isOccNR(s.x,s.y)){grid[s.y][s.x]='treeSprout';trees.push({gx:s.x,gy:s.y,st:'sprout',timer:6+Math.random()*6,seedT:15+Math.random()*20,hasSeed:false});disc_('treeSprout','Saplings detected');}b.carry=null;b.state='idle';b.idleT=2+Math.random()*4;}}}
function updBVi(b,dt){b.stT-=dt;if(b.state==='idle'){b.mv=false;b.idleT-=dt;if(b.idleT<=0){const t=wT(b,80);b.tX=t.x;b.tY=t.y;b.state='wander';b.stT=4+Math.random()*5;b.idleT=3+Math.random()*5;}}else if(b.state==='wander'){if(mvAv(b,b.tX,b.tY,dt)||b.stT<=0){b.state='idle';b.idleT=2+Math.random()*4;}}else if(b.state==='goT'){if(b.chop){if(mvAv(b,b.chop.gx*T+T/2,b.chop.gy*T+T/2,dt)){chopAt(b.chop.gx,b.chop.gy);b.chop=null;b.state='idle';b.idleT=2+Math.random()*2;}}else b.state='idle';}}
function updFrg(f,dt){f.stT-=dt;if(f.state==='idle'){f.mv=false;f.idleT-=dt;if(f.idleT<=0){const gx=Math.floor(f.x/T),gy=Math.floor(f.y/T);for(let a=0;a<20;a++){const dx=Math.floor(Math.random()*7)-3,dy=Math.floor(Math.random()*7)-3,nx=gx+dx,ny=gy+dy;if(nx>=0&&nx<GW&&ny>=0&&ny<GH&&(isRT(nx,ny)||isRA(nx,ny))){f.tX=nx*T+T/2;f.tY=ny*T+T/2;f.state='wander';f.stT=2+Math.random()*3;break;}}f.idleT=3+Math.random()*5;}}else if(f.state==='wander'){if(mvTo(f,f.tX,f.tY,dt)||f.stT<=0){f.state='idle';f.idleT=2+Math.random()*4;}}}
function updBeeI(b,dt){b.stT-=dt;if(b.state==='idle'){b.mv=false;b.idleT-=dt;if(b.idleT<=0){if(flowers.length>0){const f=flowers[Math.floor(Math.random()*flowers.length)];b.tX=f.gx*T+T/2;b.tY=f.gy*T+T/2;b.state='wander';b.stT=4+Math.random()*3;}else{const t=wT(b,60);b.tX=t.x;b.tY=t.y;b.state='wander';b.stT=3;}b.idleT=0.5+Math.random()*1.5;}}else if(b.state==='wander'){if(mvTo(b,b.tX,b.tY,dt)||b.stT<=0){b.state='idle';b.idleT=0.5+Math.random()*2;}}}
function chopAt(gx,gy){const c=grid[gy][gx];if(c==='tree'||c==='treeSprout'){const i=trees.findIndex(t=>t.gx===gx&&t.gy===gy);if(i!==-1)trees.splice(i,1);grid[gy][gx]='empty';spawnP(gx*T+T/2,gy*T+T/2,'#40a040','#208020');if(!disc['river']){disc_('river','Water flow detected');genRiver(gx,gy);}}else if(c==='bush'||c==='bushSprout'){const i=bushes.findIndex(b=>b.gx===gx&&b.gy===gy);if(i!==-1)bushes.splice(i,1);grid[gy][gx]='empty';spawnP(gx*T+T/2,gy*T+T/2,'#30aa30','#50ff50');}}
function genRiver(sx,sy){river=new Set();rPaths=[];rI=[];rGT=0;riverDone=false;riverDoneT=0;reedSD=false;for(let i=0;i<2;i++){const side=Math.floor(Math.random()*4);let ex,ey;if(side===0){ex=Math.floor(Math.random()*GW);ey=0;}else if(side===1){ex=Math.floor(Math.random()*GW);ey=GH-1;}else if(side===2){ex=0;ey=Math.floor(Math.random()*GH);}else{ex=GW-1;ey=Math.floor(Math.random()*GH);}rPaths.push(buildRP(sx,sy,ex,ey));rI.push(0);}}
function buildRP(sx,sy,ex,ey){const path=[],added=new Set();let cx=sx,cy=sy;while(cx!==ex||cy!==ey){const w=1+Math.floor(Math.random()*3);for(let dw=-Math.floor(w/2);dw<=Math.floor(w/2);dw++){for(const[wx,wy]of[[cx+dw,cy],[cx,cy+dw]]){if(wx>=0&&wx<GW&&wy>=0&&wy<GH){const k=`${wx},${wy}`;if(!added.has(k)){added.add(k);path.push({gx:wx,gy:wy,key:k});}}}}const dx=ex-cx,dy=ey-cy;if(Math.random()<0.3){cx+=Math.random()<0.5?Math.sign(dx):0;cy+=Math.random()<0.5?Math.sign(dy):0;}else{if(Math.abs(dx)>Math.abs(dy)){cx+=Math.sign(dx);if(Math.random()<0.3)cy+=Math.sign(dy);}else{cy+=Math.sign(dy);if(Math.random()<0.3)cx+=Math.sign(dx);}}cx=Math.max(0,Math.min(GW-1,cx));cy=Math.max(0,Math.min(GH-1,cy));}return path;}
function updRiver(dt){if(!rPaths.length)return;let allDone=true;for(let p=0;p<rPaths.length;p++)if(rI[p]<rPaths[p].length)allDone=false;if(allDone){if(!riverDone){riverDone=true;riverDoneT=15;}return;}rGT+=dt*20;while(rGT>=1){rGT--;for(let p=0;p<rPaths.length;p++){if(rI[p]>=rPaths[p].length)continue;const c=rPaths[p][rI[p]];if(!nearA(c.gx,c.gy,AR)){river.add(c.key);const g=grid[c.gy][c.gx];if(g!=='empty'&&g!=='altar'){let bi=bushes.findIndex(b=>b.gx===c.gx&&b.gy===c.gy);if(bi!==-1)bushes.splice(bi,1);let ti=trees.findIndex(t=>t.gx===c.gx&&t.gy===c.gy);if(ti!==-1)trees.splice(ti,1);let si=seeds.findIndex(s=>s.gx===c.gx&&s.gy===c.gy);if(si!==-1)seeds.splice(si,1);let fi=flowers.findIndex(f=>f.gx===c.gx&&f.gy===c.gy);if(fi!==-1)flowers.splice(fi,1);grid[c.gy][c.gx]='empty';}}rI[p]++;}}}
function updReeds(dt){if(riverDone&&riverDoneT>0){riverDoneT-=dt;if(riverDoneT<=0&&!reedSD){reedSD=true;spawnReedB();reedST=10+Math.random()*5;}}if(reedSD){reedST-=dt;if(reedST<=0){reedST=10+Math.random()*5;spawnReedB();}}for(const r of reeds){if(r.st==='sprout'){r.timer-=dt;if(r.timer<=0){r.st='adult';disc_('reed','Reeds detected');}}}}
function spawnReedB(){if(reeds.filter(r=>r.st==='adult').length>=MAX_REEDS)return;const rArr=Array.from(river).map(k=>{const[x,y]=k.split(',').map(Number);return{gx:x,gy:y};});if(!rArr.length)return;const n=2+Math.floor(Math.random()*3);let c=0;for(let i=0;i<100&&c<n;i++){const rt=rArr[Math.floor(Math.random()*rArr.length)];if(!reeds.some(r=>r.gx===rt.gx&&r.gy===rt.gy)){reeds.push({gx:rt.gx,gy:rt.gy,st:'sprout',timer:5});c++;}}}
function removeReed(gx,gy){const i=reeds.findIndex(r=>r.gx===gx&&r.gy===gy&&r.st==='adult');if(i===-1)return false;reeds.splice(i,1);spawnP(gx*T+T/2,gy*T+T/2,'#40a040','#60e060');disc['reedCleared']=true;if(Math.random()<0.10&&frogs.length<MAX_FROGS){frogs.push(mkA('frog',gx,gy));disc_('frog','Amphibian life form detected');}return true;}
function updFlowers(dt){if(frogs.length<3)return;flowerST-=dt;if(flowerST<=0){flowerST=3+Math.random()*7;if(flowers.length<MAX_FLOWERS){for(let a=0;a<50;a++){const gx=Math.floor(Math.random()*GW),gy=Math.floor(Math.random()*GH);if(grid[gy][gx]==='empty'&&!nearA(gx,gy,AR-1)){grid[gy][gx]='flower';flowers.push({gx,gy,col:FC[Math.floor(Math.random()*FC.length)]});disc_('flower','Floral organisms detected');break;}}}}}
function chk2x2(gx,gy){const offsets=[[-1,-1],[0,-1],[-1,0],[0,0]];for(const[ox,oy]of offsets){const x0=gx+ox,y0=gy+oy;const pts=[[x0,y0],[x0+1,y0],[x0,y0+1],[x0+1,y0+1]];const fls=[];let ok=true;for(const[px2,py2]of pts){const fi=flowers.findIndex(f=>f.gx===px2&&f.gy===py2);if(fi===-1){ok=false;break;}fls.push(fi);}if(ok&&bees.length<MAX_BEES){const cx2=(x0+0.5)*T+T/2,cy2=(y0+0.5)*T+T/2;fls.sort((a,b)=>b-a);for(const fi of fls){grid[flowers[fi].gy][flowers[fi].gx]='empty';flowers.splice(fi,1);}const bee=mkA('bee',0,0);bee.x=cx2;bee.y=cy2;bees.push(bee);spawnP(cx2,cy2,'#ffe030','#ffaa00');disc_('bee','Pollinator attracted');return true;}}return false;}
function chkSpawn(){const bc=cntB(),tc=cntT();const tR=Math.min(MRB,Math.max(totalSP>=3||bushes.length>0?1:0,Math.floor(bc/5)));while(rB.length<tR){const a=Math.random()*Math.PI*2,d=15+Math.random()*10;rB.push(mkA('redBird',CX+Math.cos(a)*d,CY+Math.sin(a)*d));if(rB.length===1)disc_('redBird','Red bird detected');}if(bc>=3){const tBB=Math.min(MBB,Math.max(1,1+Math.floor(tc/3)));while(bB.length<tBB){const a=Math.random()*Math.PI*2,d=15+Math.random()*10;const b=mkA('blueBird',CX+Math.cos(a)*d,CY+Math.sin(a)*d);if(bB.length===0){b.isFirst=true;b.hPF=false;}bB.push(b);if(bB.length===1)disc_('blueBird','Blue bird detected');}}if(tc>=6){const tBV=Math.min(MAX_BV,Math.floor((tc-10)/10));while(beavers.length<tBV){const a=Math.random()*Math.PI*2,d=10+Math.random()*8;beavers.push(mkA('beaver',CX+Math.cos(a)*d,CY+Math.sin(a)*d));if(beavers.length===1)disc_('beaver','Beaver detected');}}}
function updBushes(dt){for(const b of bushes){if(b.st==='sprout'){b.timer-=dt;if(b.timer<=0){b.st='bush';grid[b.gy][b.gx]='bush';spawnP(b.gx*T+T/2,b.gy*T+T/2,'#30aa30','#50ff50');disc_('bush','Mature bushes');}}}}
function updTrees(dt){let tsOn=0;for(const t of trees)if(t.st==='tree'&&t.hasSeed)tsOn++;
  for(const t of trees){if(t.st==='sprout'){t.timer-=dt;if(t.timer<=0){t.st='tree';grid[t.gy][t.gx]='tree';t.hasSeed=false;t.seedT=15+Math.random()*20;spawnP(t.gx*T+T/2,t.gy*T+T/2,'#20cc40','#50ff50');disc_('tree','Trees detected');}}else if(t.st==='tree'&&!t.hasSeed){if(tsOn+tSP.length<MTS){t.seedT-=dt;if(t.seedT<=0){t.seedT=20+Math.random()*30;if(Math.random()<0.3){t.hasSeed=true;tsOn++;disc_('treeSeed','Tree seed');}}}}}}
function updTasks(){let ch=false;for(const t of TASKS){if(!tasksDone.has(t.id)&&t.check()){tasksDone.add(t.id);ch=true;showTB();}}if(ch&&galOpen&&galPage==='tasks')renderPage();}

